(ns share.dicts.en)

(def dicts
  {:simplified_chinese "Simplified Chinese"
   :traditional_chinese "Traditional Chinese"
   :japanese "Japanese"
   :english "English"
   :german "German"
   :french "French"
   :spanish "Spanish"
   :turkish "Turkish"
   :italian "Italian"
   :portuguese "Portuguese"
   :swedish "Swedish"
   :danish "Danish"
   :norwegian "Norwegian"
   :dutch "Dutch"
   :polish "Polish"
   :indonesian "Indonesian"
   :hindi "Hindi"
   :russian "Russian"
   :korean "Korean"
   :thai "Thai"
   :arabic "Arabic"
   :bengali "Bengali"
   :punjabi "Punjabi"
   :switch-to "Switch to "
   :hot "popular"
   :latest "latest"
   :latest-posts "Posts"
   :latest-comments "Comments"
   :expand "Expand"
   :collapse "Collapse"
   :submit "Submit"
   :cancel "Cancel"
   :report "Report"
   :delete "Delete"
   :reply "Reply"
   :comment "Comment"
   :post "Post"
   :title "Title"
   :reason "Reason"
   :user "User"
   :ignore-it "Ignore it"
   :disable-user "Disable this user for 3 days"
   :block-user "Block this user."
   :no-more-reports "No more reports."
   :no-more-notifications "No more notifications."
   :general "general"
   :purpose "Purpose"
   :optional "optional"
   :new-message "New message"
   :create "Create"
   :your-thoughts-here "Your thoughts here"
   :post-comment "Post Comment"
   :back "Back"
   :preview "Preview"
   :like-it "Like it"
   :unlike-it "Unlike it"
   :like "Like"
   :unlike "Unlike"
   :edit "Edit"
   :update "Update"
   :replies "replies"
   :hot-posts "Hot posts"
   :signin "Sign In"
   :slogan "A place to discuss tech articles or books."
   :members "members"
   :admins "Moderators"
   :support "support"
   :contact "Contact"
   :terms "Terms"
   :code-of-conduct "Code of Conduct"
   :email "Email"
   :invalid-email "Invalid email."
   :signin-github "Sign in with Github"
   :signup-email "Sign up with Email"
   :invalid-code "Invalid code"
   :please-input-verify-code "Please input your verify code"

   :as-below-deleted " as below was deleted."
   :disable-account-notification "Your account will be disabled for the next 3 days, you will not be able to post or comment."
   :block-notification "Sorry, you have been blocked: "
   :promote-notification "promoted you to be one of the moderators: "
   :new-comment "New comment: "
   :post-new-comment " has a new comment"
   :new-comment-to-my-comment "New reply to my comment"
   :dismiss-all "Dismiss all"
   :photo-upload "Add photos, support at most 9 pictures once."
   :post-title-warning "Title should be 8 ~ 80 characters long."
   :post-tags-warning "Please specify at least 1 tag."
   :post-body-placeholder "Write your thoughts..."
   :publish "Publish"
   :settings "Settings"
   :publish-to "Publish"
   :vote "Vote"
   :unvote "Unvote"
   :down "Down"
   :undown "Undown"
   :no-more-posts "No more posts."
   :more "More"
   :be-the-first "Write your thoughts"
   :no-posts-yet "No posts yet."
   :no-comments-yet "No comments yet."
   :no-drafts-yet "No drafts yet."
   :no-links-yet "No links yet."
   :link "Link"
   :close "Close"
   :post-permalink-copied "Post permalink copied!"
   :comment-permalink-copied "Comment permalink copied!"
   :tweet "Tweet"
   :share "Share"
   :add "Add"
   :post-not-available "Sorry, this post is not available!"

   ;; root
   :search "Search"
   :search-posts "Search posts..."
   :reports "Reports"
   :write-new-post "Write an article"
   :new-post-description "Had a question, or got something inspiring to share? Your friends are waiting!"
   :root-title "A place to discuss tech articles or books."
   :root-description "Putchar is a place to discuss tech articles or books. Posts support multiple formats include Markdown and Org mode."
   :go-to-profile "Posts"
   :profile-updated "Profile updated!"
   :sign-out "Sign Out"
   :search-result "Search result: "
   :empty-search-result "no matched posts."

   ;; user
   :screen-name-taken "Username was already taken."
   :username-length-warning "Your username can be up to 15 characters long."
   :email-exists "Email address already exists."
   :full-name "Full name"
   :full-name-warning "Full name should not be blank."
   :unique-username "Username"
   :bio "Bio"
   :bio-placeholder "Introduce yourself, optional."
   :click-circle-add-avatar "Upload an avatar"
   :languages "Languages"
   :welcome "Welcome"
   :signup "Sign Up"
   :your-email "Your email:"
   :cached-change-avatar "Your avatar changed, it may take several minutes to clear the cache."
   :change-avatar "Change avatar"
   :update-profile "Update profile"
   :votes "Votes"
   :my-votes "Votes"
   :my-drafts "Drafts"
   :old "old"
   :new "new"
   :best "best"
   ;; handlers
   ;; comment
   :new-comment-received "New comment!"
   :bad-happened "Something bad happend, please try later."

   :post-published "Post published!"
   :post-updated "Post updated!"
   :post-deleted "Post deleted."
   :post-delete-confirm "Are you sure you want to delete this post?"
   :user-delete-confirm "Are you sure you want to delete this account?"
   :share-link "[link]"

   ;; report
   :report-sent "Report sent!"

   ;; user
   :please-check-your-email "Please check your email!"

   :pick-a-username "Pick a username"
   :username "Username"
   :username-exists "Username already exists."
   :spam "This is spam"
   :abusive "This is abusive or harassing"
   :other-issues "Other issues"

   ;; time
   :d "d"
   :h "h"
   :m "m"
   :s "s"
   :now "now"

   :export-my-data "Export my data"
   :delete-this-account "Delete this account"
   :invites-sent "Invites sent successfully!"
   :twitter-handle "Twitter Handle"
   :github-handle "Github Handle"

   :public "Public"
   :description "Description"
   :upload-a-cover "Upload a cover"
   :cover "Cover"
   :bugs "Bug reports"
   :feature-requests "Feature Requests"
   :safety "Safety"
   :social "Social"
   :team-support "Team Support"
   :notifications "Notifications"
   :star "Star"
   :unstar "Unstar"
   :about "About"
   :report-delete-confirmation "Are you sure you want to delete this?"
   :no-replies-yet "No replies yet."
   :back-to "Back to "
   :not-found "Not Found"
   :draft "Draft"
   :drafts "Drafts"
   :saving "saving..."
   :sort "Sort"
   :latest-reply "latest reply"
   :created-at "Created at"
   :last-reply-at "Latest reply at"
   :updated-at "Updated at"
   :loading "loading..."
   :contact-us "Contact Us"
   :website-name "Putchar"
   :popular "Popular"
   :new-created "Recent posts"
   :welcome-to-putchar "Welcome to Putchar!"
   :activate-your-account "Sign In"
   :last-reply-by "Last reply by: "
   :frequent-poster "Frequent poster: "
   :posted-by "Posted by: "
   :email-login-placeholder "Enter your email address"
   :report-this-post "Report this post"
   :delete-this-post "Delete this post"
   :report-this-comment "Report this comment"
   :delete-this-comment "Delete this comment"
   :tags "Tags"
   :add-tags-label "Add tags (at least 1 tag):"
   :add-tags "Up to 3 tags, seperated by commas..."
   :email-notification-settings "Email notification settings"
   :email-notification-settings-text "Email me when someone replies to my post or mentions my @username."
   :my-data "My Data"
   :about-text "

# About

Putchar.org is a place to discuss articles or [books](/books).

## Features

* Each book has its own posts and followers.

  For example, [Purely functional data structures](/book/7).

* Post format supports Markdown and Emacs Org-mode.

* You can [select multiple languages](/settings#languages) you'd like to see throughout the site.

  Yes, not just English.

## FAQ

* Who are the team behind Putchar?

  Currently only myself, [@tiensonqin](/@tiensonqin).

* What is it built with?

  [Clojurescript](https://clojurescript.org/) with [React](https://reactjs.org/).

 The server side is [Clojure](https://clojure.org/) backed by a Postgres database and Redis cache.

* Is it open source?

  Yes, https://github.com/tiensonqin/putchar.
"
   :misc "Misc"
   :dont-show-vote-numbers "Don't show vote numbers"
   :undo "Undo"
   :required "Required"
   :login-to-comment "You must be logged in to comment"
   :go-to-fullscreen "Go to fullscreen"
   :select-primary-language "Select post primary language"
   :select-primary-language-explain "User who doesn't follow this language won't see this post."
   :select-which-languages "Select which languages of posts you'd like to see."
   :go-to-home "Go to home"
   :signin-with-email "Sign in with Email"
   :light-theme "Light theme"
   :dark-theme "Dark theme"
   :no-stats-yet "No stats yet."
   :recent-7-days "Recent 7 days"
   :views "views"
   :reads "reads"
   :stats "Stats"
   :posts "Posts"
   :language-default-choice "Set \"%s\" as my default choice."
   :language-must-be-chosen "Language must be chosen!"
   :post-primary-language "Post primary language"
   :is-my-default-language-choice " is my default language choice, "
   :change-it-to "change it to "
   :privacy "Privacy"
   :comments "comments"
   :name "Name"
   :authors "Authors"
   :authors-placeholder "Markdown links are supported..."
   :change "Change"
   :show-all "Show all"
   :no-votes-yet "No votes yet."
   :books "Books"
   :book "book"
   :add-a-book "Add a book"
   :website "Website"
   :introduction "View introduction"
   :moderation-logs "Moderation Logs"
   :join "Join"
   :leave "Leave"
   :hot-tags "Hot tags"
   :or-submit-a-link "Or submit a link"
   :submit-a-link "Submit a link"
   :links "Links"
   })
