(ns share.dicts.en)

(def dicts
  {:simplified_chinese "Simplified Chinese"
   :traditional_chinese "Traditional Chinese"
   :japanese "Japanese"
   :english "English"
   :german "German"
   :french "French"
   :spanish "Spanish"
   :turkish "Turkish"
   :italian "Italian"
   :portuguese "Portuguese"
   :swedish "Swedish"
   :danish "Danish"
   :norwegian "Norwegian"
   :dutch "Dutch"
   :polish "Polish"
   :indonesian "Indonesian"
   :hindi "Hindi"
   :russian "Russian"
   :korean "Korean"
   :thai "Thai"
   :arabic "Arabic"
   :bengali "Bengali"
   :punjabi "Punjabi"
   :switch-to "Switch to "
   :all-channels "All channels"
   :hot "popular"
   :latest "latest"
   :latest-posts "Posts"
   :latest-comments "Comments"
   :groups "Groups"
   :lambdahackers-hot-groups "Hot groups on lambdahackers"
   :add-more-groups "Add more groups"
   :direct-messages "Direct messages"
   :expand "Expand"
   :collapse "Collapse"
   :submit "Submit"
   :cancel "Cancel"
   :report "Report"
   :private "Private"
   :delete "Delete"
   :reply "Reply"
   :comment "Comment"
   :post "Post"
   :title "Title"
   :reason "Reason"
   :user "User"
   :ignore-it "Ignore it"
   :confirm-delete "Are you sure you want to delete this "
   :disable-user "Disable this user for 3 days"
   :block-user "Block this user from current group"
   :no-more-reports "No more reports."
   :no-more-notifications "No more notifications."
   :general "general"
   :channel-name "Channel name"
   :purpose "Purpose"
   :rules "Rules"
   :optional "optional"
   :create-new-channel "Create new channel"
   :new-message "New message"
   :create "Create"
   :your-thoughts-here "Your thoughts here"
   :post-comment "Post Comment"
   :back "Back"
   :preview "Preview"
   :like-it "Like it"
   :unlike-it "Unlike it"
   :like "Like"
   :unlike "Unlike"
   :edit "Edit"
   :update "Update"
   :replies "replies"
   :group "Group"
   :group-name "Group name"
   :name-warning "Name should be 1 ~ 24 characters long."
   :purpose-warning "Purpose should be 2 ~ 1024 characters long."
   :upload-a-logo "Upload a logo"
   :upload-a-photo "Upload a photo"
   :change-group-logo "Change group logo"
   :logo-changed-notification "Logo changed, it may take several minutes to clear the cache."
   :create-new-group "Create a new group"
   :please-upload-a-logo "Please upload a logo."
   :join-group "Join group"
   :not-exists-yet " not exists yet, time to "
   :create-it-yourself "Create it yourself!"
   :update-group "Update group"
   :related-groups "Related groups"
   :add-related-groups "Add related groups"
   :commas-seperated "Groups names should be seperated by commas"
   :hot-posts "Hot posts"
   :admin "Moderator"
   :channels "Channels"
   :channel "channel"
   :add-more-channels "Add more channels"
   :invite "Invite members"
   :invite-members-placeholder "Emails should be seperated by commas, at most 20 email addresses once."
   :send "Send"
   :promote-member "Promote a member to Moderator"
   :promote "Promote"
   :leave-group "Leave group"
   :join "Join"
   :signin "Sign In"
   :explore-groups "Explore groups"
   :create-a-group "Create your group"
   :your "Your "
   :to " to "
   :slogan "Where programmers discuss and share their thoughts."
   :anyone-create-group "Anyone can create a public group"
   :unlimited "unlimited "
   :members "members"
   :admins "Moderators"
   :group-members "Members"
   :vote-share "Group members can post, vote, comment or share links."
   :admin-add-channel "There are "

   :only-subscribe "So you only subscribe to your interested content."
   :writing "Writing"
   :support "support"
   :limited-markdown-support "Also with limited Markdown support."
   :translation-links "Translation links"
   :translation-text "So you can translate an article and add a link to it."
   :github-sync "Github Sync"
   :github-sync-text "All of your posts will be pushed to your specific repo."
   :contact "Contact"
   :privacy "Privacy"
   :terms "Terms"
   :code-of-conduct "Code of Conduct"
   :not-joined-any "You haven't joined any groups."
   :email "Email"
   :invalid-email "Invalid email."
   :signin-github "Sign in with Github"
   :signup-email "Sign up with Email"
   :invalid-code "Invalid code"
   :please-input-verify-code "Please input your verify code"

   :as-below-deleted " as below was deleted."
   :disable-account-notification "Your account will be disabled for the next 3 days, you will not be able to post or comment in the group: "
   :block-notification "Sorry, you have been blocked from the group: "
   :promote-notification "promoted you to be the moderator of group: "
   :new-comment "New comment: "
   :post-new-comment " has a new comment"
   :new-comment-to-my-comment "New reply to my comment"
   :dismiss-all "Dismiss all"
   :photo-upload "Add photos, support at most 9 pictures once."
   :post-title-warning "Title should be 4 ~ 64 characters long."
   :post-body-placeholder "Share your thoughts or just a link..."
   :publish "Publish"
   :settings "Settings"
   :publish-to "Publish to: "
   :vote "Vote"
   :unvote "Unvote"
   :down "Down"
   :undown "Undown"
   :no-more-posts "No more posts."
   :more "More"
   :be-the-first "Start to write a post"
   :no-posts-yet "No posts yet."
   :no-comments-yet "No comments yet."
   :no-drafts-yet "No drafts yet."
   :no-links-yet "No links yet."
   :no-bookmarks-yet "No bookmarks yet."
   :link "Link"
   :close "Close"
   :post-permalink-copied "Post permalink copied!"
   :comment-permalink-copied "Comment permalink copied!"
   :group-link-copied "Group link copied!"
   :tweet "Tweet"
   :share "Share"
   :add-translation-link "Add translation link"
   :add "Add"
   :which-language-link "Which language does this link translated to?"
   :post-not-available "Sorry, this post is not available!"

   ;; root
   :search "Search"
   :search-groups "Search groups..."
   :search-channels "Search channels..."
   :search-posts "Search posts..."
   :reports "Reports"
   :write-new-post "New post"
   :new-post-description "Had a question, or got something inspiring to share? Your friends are waiting!"
   :root-title "Lambdahackers - Where programmers discuss and share their thoughts."
   :root-description "Lambdahackers is a community for programmers to discuss and share their thoughts. You can read news, or join your favorite groups to post, comment or vote. You can also create a community as long as it's related to programmers."
   :go-to-profile "Posts"
   :profile-updated "Profile updated!"
   :sign-out "Sign Out"
   :search-result "Search result: "
   :empty-search-result "no matched posts."

   ;; user
   :screen-name-taken "Username was already taken."
   :username-length-warning "Your username can be up to 15 characters long."
   :email-exists "Email address already exists."
   :full-name "Full name"
   :full-name-warning "Full name should not be blank."
   :unique-username "Username"
   :website "Website"
   :website-placeholder "Your website, optional."
   :bio "Bio"
   :bio-placeholder "Introduce yourself, optional."
   :click-circle-add-avatar "Upload an avatar"
   :join-at-least "Select your interests:"
   :languages "Languages"
   :countries "Countries"
   :football-teams "Football teams"
   :nba-teams "NBA teams"
   :interests "Interests"
   :cities "Cities"
   :done "Done"
   :welcome "Welcome"
   :signup "Sign Up"
   :your-email "Your email:"
   :cached-change-avatar "Your avatar changed, it may take several minutes to clear the cache."
   :change-avatar "Change avatar"
   :update-profile "Update profile"
   :take-some-notes "Take some notes"
   :voted-posts "Voted posts"
   :followed-posts "My followed"
   :votes "Votes"
   :my-votes "Votes"
   :my-drafts "Drafts"
   :old "old"
   :new "new"
   :best "best"
   :follow-conversation "Follow Conversation"
   :unfollow-conversation "Unfollow Conversation"
   ;; handlers
   ;; comment
   :new-comment-received "New comment!"
   ;; group
   :group-updated "Group updated!"
   :has-been-promoted " has been promoted!"
   :user-not-exists "Please check the username, it doesn't exists as now."
   :user-not-joined "Sorry, this user hasn't joined the group."
   :bad-happened "Something bad happend, please try later."

   :post-published "Post published!"
   :post-updated "Post updated!"
   :post-deleted "Post deleted."
   :post-delete-confirm "Are you sure you want to delete this post?"
   :user-delete-confirm "Are you sure you want to delete this account?"
   :translation-link-added "Translation link added!"
   :share-link "[link]"

   ;; report
   :report-sent "Report sent!"

   ;; user
   :please-check-your-email "Please check your email!"

   :username "Username"
   :username-exists "Username already exists."
   :groups-order-saved "Groups order saved!"
   :spam "This is spam"
   :abusive "This is abusive or harassing"
   :break-group-rules "It breaks group rules"
   :other-issues "Other issues"

   ;; time
   :d "d"
   :h "h"
   :m "m"
   :s "s"
   :now "now"

   :export-my-data "Export my data"
   :delete-this-account "Delete this account"
   :invites-sent "Invites sent successfully!"
   :twitter-handle "Twitter Handle"
   :github-handle "Github Handle"

   :connect-github "Setup Github Sync"
   :github-repo-link-placeholder "Your repo link"
   :your-github-repo "Github repo: "

   :public "Public"
   :invite-only "Invite Only"
   :join-to-comment "Join this group to comment"

   :description "Description"
   :upload-a-cover "Upload a cover"
   :cover "Cover"
   :try-search-placeholder "Add your language or city..."
   :bugs "Bug reports"
   :feature-requests "Feature Requests"
   :safety "Safety"
   :social "Social"
   :team-support "Team Support"
   :stared-channels "Stared channels"
   :notifications "Notifications"
   :star "Star"
   :unstar "Unstar"
   :about "About"
   :back-to-top "BACK TO TOP"
   :edit-channel "Edit channel"
   :all-members "All members"
   :see-all "See all"
   :free-features "Free features"
   :public-groups "Public groups."
   :unlimited-members "Unlimited members."
   :up-to-10-moderators "Up to 10 moderators."
   :unlimited-channels "Unlimited channels."
   :search-indexed "Search indexed."
   :private-group "Private group"
   :each-costs "Each costs "
   :ten-per-month "$10/month"
   :thats-all ", that's all."
   :create-your-group "Create your group"
   :login-to-create-your-group "Login to create your group"
   :we-are-working-hard "We're working hard to be a better place for your favorite groups. Your early support definitely helps – thank you! "
   :here-is-what "Here's what's unlocked on PRO:"
   :no-ads "No ads."
   :a-pro-badge "A PRO badge under your avatar everywhere on lambdahackers."
   :more-to-come "More to come."
   :pro-costs "PRO costs "
   :nine-nine-per-month  "$0.99/month"
   :you-can-cancel " and you can cancel at any time."
   :upgrade-to-pro "Upgrade to PRO"
   :login-to-upgrade-to-pro "Login to upgrade to PRO"
   :pricing "Pricing"
   :thanks-for-your-support "Thanks for your support!"
   :links "Links"
   :poll "Poll"
   :choice "Choice"
   :add-a-choice "Add a choice"
   :choice-votes "Votes"
   :choice-saved "Thanks for voting!"
   :poll-disabled "The poll was disabled successfully."
   :lock-this-poll "Lock this poll"
   :delete-this-poll "Delete this poll"
   :locked "Locked"
   :set-as-cover "Set as cover"
   :save "save"
   :cover-title "Title"
   :cover-subtitle "SubTitle"
   :cover-button-text "Button Text"
   :edit-cover "Edit cover"
   :upload "Upload"
   :photo-deleted "The photo was deleted."
   :delete-photo-confirmation "Are you sure you want to delete this photo?"
   :report-delete-confirmation "Are you sure you want to delete this?"
   :group-cover-changed "Group cover has been changed successfully."
   :skip "Skip"
   :no-replies-yet "No replies yet."
   :back-to "Back to "
   :not-found "Not Found"
   :draft "Draft"
   :drafts "Drafts"
   :select-group "Choose a group: "
   :saving "saving..."
   :sort "Sort"
   :latest-reply "latest"
   :created-at "Created at"
   :last-reply-at "Latest reply at"
   :updated-at "Updated at"
   :lambdahackers-group "Lambdahackers community"
   :already-20-groups "Sorry, you need to leave a group first to join this group."
   :loading "loading..."
   :contact-us "Contact Us"
   :website-name "Lambdahackers"
   :popular "Popular"
   :new-created "new"
   :bookmark "Bookmark"
   :unbookmark "Unbookmark"
   :bookmarks "Bookmarks"
   :welcome-to-lambdahackers "Welcome to Lambdahackers!"
   :activate-your-account "Sign In"
   :last-reply-by "Last reply by: "
   :posted-by "Posted by: "
   :add-to-wiki "Add to Wiki"
   :email-login-placeholder "Enter your email address"
   :github-connect-text "[NOTE]
====
So you can git commit a new post, and it will be automatically published on Lambdahackers, and vice versa.
====

.Steps
****
. You grant us with the `public_repo` permission.

. We create a repo called *lambdahackers-blog* for syncing, you can change its name later.

. We add a webhook to listen for all push events of that repo.
****"
   :report-this-post "Report this post"
   :delete-this-post "Delete this post"
   :report-this-comment "Report this comment"
   :delete-this-comment "Delete this comment"

   :add-tags "Add tags (up to 5)..."
   :email-notification-settings "Email notification settings"
   :email-notification-settings-text "Email me when someone replies to my post or mentions my @username."
   :my-data "My Data"
   :watch "Watch"
   :watch-text "You will be notified of every new reply in this topic."
   :default "Default"
   :default-text "You will be notified if someone mentions your @name or replies to you."
   :mute "Mute"
   :mute-text "You will never be notified of anything about this topic."
   :about-description "Lambdahackers is a open source community platform built for the programmers to discuss and share their thoughts. "
   :about-text "
=== Features

* Anyone can *create any group* as long as it's programmers related.
  Group supports channels.
* *Git commit to publish* your posts. :tada:
  You can commit a new post (support both Markdown and Asciidoctor) to Github, the post will be automatically published on Lambdahackers, and vice versa.
* A simple *blog* for everyone.
  It supports tags, permalinks.
  Series, custom domain and more features are coming...

=== FAQ

* Who are the team behind Lambdahackers?
  Currently only myself, @tiensonqin.

* How do you earn money?
  I won't sell your personal data.
  I won't show you ads except for some community sponsors.

* What is it built with?
  https://clojurescript.org/[Clojurescript] with https://reactjs.org/[React].
 The server side is https://clojure.org/[Clojure] backed by a https://www.postgresql.org/[Postgres] database and https://redis.io/[Redis] cache.

* I want to be the moderator of a specific group, how?
  You can contact the moderators for that specific group, or you can email me for now: tiensonqin@gmail.com.
"
   })
