(ns share.dicts.zh-cn)

(def dicts
  {:simplified_chinese "简"
   :traditional_chinese "繁"
   :japanese "日"
   :english "英"
   :german "德"
   :french "法"
   :spanish "西班牙"
   :turkish "土耳其"
   :italian "意大利"
   :portuguese "葡萄牙"
   :swedish "瑞典"
   :danish "丹麦"
   :norwegian "挪威"
   :dutch "荷兰"
   :polish "波兰"
   :indonesian "印尼"
   :hindi "印地"
   :russian "俄"
   :korean "韩"
   :thai "泰"
   :arabic "阿拉伯"
   :bengali "孟加拉"
   :punjabi "旁遮普"
   :switch-to "切换为"
   :hot "热门"
   :latest "最新"
   :latest-posts "文章"
   :latest-comments "评论"
   :all-channels "所有分类"
   :groups "小组"
   :lambdahackers-hot-groups "热门小组"
   :add-more-groups "加入更多小组"
   :direct-messages "私信"
   :expand "展开"
   :collapse "收回"
   :submit "提交"
   :cancel "取消"
   :report "举报"
   :private "私密"
   :delete "删除"
   :reply "回复"
   :comment "评论"
   :post "文章"
   :title "文章标题"
   :reason "原因"
   :user "用户"
   :ignore-it "不管"
   :confirm-delete "你确定要删除 "
   :disable-user "禁言三天"
   :block-user "加入黑名单"
   :no-more-reports "暂时没有更多举报了"
   :no-more-notifications "没有未读通知"
   :general "默认"
   :channel-name "分类名称"
   :purpose "描述"
   :rules "规则"
   :optional "可不填"
   :create-new-channel "创建新的分类"
   :new-message "新的消息"
   :create "创建"
   :your-thoughts-here "你的想法是什么?"
   :post-comment "发布评论"
   :back "返回"
   :preview "预览"
   :like-it "喜欢"
   :unlike-it "取消喜欢"
   :like "喜欢"
   :unlike "取消喜欢"
   :edit "编辑"
   :update "修改"
   :replies "条评论"
   :group "小组"
   :group-name "小组名称"
   :name-warning "名称长度为大于 1 且不超过 24 个字符。"
   :purpose-warning "描述长度为大于 2 且不超过 1024 个字符。"
   :upload-a-logo "上传 LOGO"
   :upload-a-photo "上传照片"
   :change-group-logo "替换 LOGO"
   :logo-changed-notification "Logo 已经修改， 需要重新刷新页面。"
   :create-new-group "创建新的小组"
   :please-upload-a-logo "请上传小组的 LOGO。"
   :join-group "加入小组"
   :not-exists-yet " 不存在， 你可以 "
   :create-it-yourself "自己创建!"
   :update-group "修改小组"
   :related-groups "相关小组"
   :add-related-groups "添加相关小组"
   :commas-seperated "请用逗号分隔小组名称"
   :hot-posts "热门帖子"
   :admin "管理员"
   :channels "分类"
   :channel "分类"
   :add-more-channels "添加更多分类"
   :invite "邀请朋友"
   :invite-members-placeholder "请用逗号分隔邮箱地址, 一次支持最多 20 个邮箱地址"
   :send "发送"
   :promote-member "提升其他用户为管理员"
   :promote "提升"
   :leave-group "离开小组"
   :join "加入"
   :signin "登录"
   :explore-groups "热门小组"
   :create-a-group "创建我的小组"
   :your "你的 "
   :to " 用来 "
   :slogan "码农的一亩三分地儿"
   :anyone-create-group "任何人都可以创建公开小组。"
   :unlimited ""
   :members "成员"
   :admins "管理员"
   :group-members "成员"
   :vote-share "小组成员可以赞， 评论， 分享链接或者发布文章。"
   :admin-add-channel "小组支持"
   :only-subscribe "你可以只关注自己喜欢的内容。"
   :writing "写文章"
   :support "支持"
   :limited-markdown-support "支持部分 Markdown 语法。"
   :translation-links "贡献翻译"
   :translation-text "你可以翻译一篇文章，添加原链接后分享给你的朋友。"
   :github-sync "Github 同步"
   :github-sync-text "你的所有文章都会提交到指定的仓库中。"
   :contact "联系我们"
   :privacy "隐私"
   :terms "条款"
   :code-of-conduct "社区规则"
   :not-joined-any "你还没有加入任何小组。"
   :email "邮箱"
   :invalid-email "无效邮箱。"
   :signin-github "Github 登录"
   :signup-email "邮箱注册"
   :invalid-code "无效的验证码"
   :please-input-verify-code "请输入验证码"

   ;; notifications
   :as-below-deleted " 被删除了。"
   :disable-account-notification "你的账号已被禁言三天， 小组: "
   :block-notification "你已被加入小组黑名单:  "
   :promote-notification "提升你为小组管理员: "
   :new-comment "新评论: "
   :post-new-comment " 有新的评论"
   :new-comment-to-my-comment "回复了你的评论"
   :dismiss-all "清空"

   ;; post
   :photo-upload "上传图片， 一次最多可以上传 9 张图片， 支持拖拽"
   :post-title-warning "标题长度大于 4 且不超过 64 个字符。"
   :post-body-placeholder "分享你的想法， 或者有意义的链接..."
   :publish "发布"
   :settings "设置"
   :publish-to "发布到: "
   :vote "顶"
   :unvote "取消"
   :down "踩"
   :undown "取消"
   :no-more-posts "没有更多了。"
   :more "更多"
   :be-the-first "发帖"
   :no-posts-yet "暂时没有文章。"
   :no-comments-yet "暂时没有评论。"
   :no-drafts-yet "暂时没有草稿。"
   :no-links-yet "暂时未发布链接。"
   :no-bookmarks-yet "暂时没有收藏。"
   :link "链接"
   :close "关闭"
   :post-permalink-copied "文章链接已复制!"
   :comment-permalink-copied "评论链接已复制!"
   :group-link-copied "小组链接已复制!"
   :tweet "发推"
   :share "分享"
   :add-translation-link "添加翻译链接"
   :add "添加"
   :which-language-link "这个链接翻译为哪种语言?"
   :post-not-available "当前文章不存在。"

   ;; root
   :search "搜索"
   :search-groups "搜索小组..."
   :search-channels "搜索小组分类..."
   :search-posts "搜索文章..."
   :reports "举报"
   :write-new-post "写文章"
   :new-post-description "写一篇新的文章。"
   :root-title "码农的一亩三分地儿 - Lambdahackers"
   :root-description "Lambdahackers 是一个码农之间互相讨论和分享学习的社区。任何人都可以加入自己喜欢的小组， 比如编程语言, 城市, 兴趣等。小组成员可以发帖, 分享链接, 讨论以及投票等。你也可以创建自己喜欢的社区, 只要跟码农相关即可。"
   :go-to-profile "文章"
   :profile-updated "已保存!"
   :sign-out "注销"

   ;; search
   :search-result "搜索结果: "
   :empty-search-result "没有匹配的文章。"

   ;; user
   :screen-name-taken "用户名已经被占用。"
   :username-length-warning "用户名长度不可以超过 15 个字符。"
   :email-exists "邮箱已存在。"
   :full-name "姓名"
   :full-name-placeholder "姓名, 可不填"
   :full-name-warning "姓名不可以为空。"
   :unique-username "用户名"
   :website "网站"
   :website-placeholder "你的网站， 可不填。"
   :bio "简介"
   :bio-placeholder "介绍下自己吧， 可不填。"
   :click-circle-add-avatar "添加头像"
   :join-at-least "选择你的兴趣: "
   :languages "语言"
   :countries "国家"
   :football-teams "足球"
   :nba-teams "NBA"
   :interests "兴趣"
   :cities "热门城市"
   :done "完成"
   :welcome "欢迎"
   :signup "注册"
   :your-email "你的邮箱:"
   :cached-change-avatar "你的头像已经修改， 需要重新刷新页面。"
   :change-avatar "修改头像"
   :update-profile "修改个人设置"
   :take-some-notes "写笔记"
   :voted-posts "顶过的文章"
   :votes "顶"
   :my-votes "顶过的文章"
   :my-drafts "草稿"
   :old "默认排序"
   :new "最新"
   :best "赞"
   :follow-conversation "有新的评论通知我"
   :unfollow-conversation "取消评论通知"

   :spam "这是一篇垃圾文章/评论"
   :abusive "谩骂， 侮辱 或者骚扰"
   :break-group-rules "违反小组法规"
   :other-issues "其他问题"

   ;; handlers
   ;; comment
   :new-comment-received "有新的评论!"
   ;; group
   :group-updated "小组已更新!"
   :has-been-promoted " 已被提为 Admin!"
   :user-not-exists "请确认用户名， 此用户名并不存在。"
   :user-not-joined "此用户还没有加入小组。"
   :bad-happened "操作失败， 请稍后重新尝试， 或者联系我们。"

   :post-published "文章已发布， :)"
   :post-updated "文章已更新!"
   :post-deleted "文章已删除。"
   :post-delete-confirm "你确定要删除这篇文章吗?"
   :translation-link-added "翻译链接已添加， 谢谢!"
   :share-link "「链接」"

   ;; report
   :report-sent "举报已发送， 谢谢!"

   ;; user
   :please-check-your-email "请查收你的邮箱!"

   :username-exists "用户名已经被占用。"
   :username "用户名"
   :groups-order-saved "小组顺序已保存!"

   ;; time
   :d "天前"
   :h "小时前"
   :m "分钟前"
   :s "秒"
   :now "刚刚"

   :export-my-data "导出我的数据"
   :delete-this-account "永久删除账号"
   :invites-sent "邀请已发送!"
   :twitter-handle "Twitter 用户名"
   :github-handle "Github 用户名"

   :connect-github "设置 Github 同步"
   :github-repo-link-placeholder "你的仓库地址"
   :your-github-repo "你的 Github 仓库: "

   :public "公开"
   :invite-only "邀请"
   :join-to-comment "加入小组就可以评论了"

   :description "简介"
   :upload-a-cover "上传封面"
   :cover "封面"

   :try-search-placeholder "添加你的语言或城市..."
   :bugs "Bug 反馈"
   :feature-requests "其他功能"
   :safety "隐私安全"
   :social "社交"
   :team-support "支持"
   :stared-channels "已收藏分类"
   :notifications "通知"
   :star "收藏"
   :unstar "取消收藏"
   :about "关于"
   :back-to-top "回到顶部"
   :edit-channel "修改分类"
   :all-members "小组成员"
   :see-all "查看所有"
   :free-features "免费功能"
   :public-groups "公开小组。"
   :unlimited-members "不限制人数。"
   :up-to-10-moderators "最多 10 个管理员。"
   :unlimited-channels "不限制分类个数。"
   :search-indexed "可以搜索帖子。"
   :private-group "私密小组。"
   :each-costs "每个私密小组需要"
   :ten-per-month "$10/每月"
   :thats-all "。"
   :create-your-group "创建你的小组"
   :login-to-create-your-group "登录创建你的小组"
   :we-are-working-hard "我们一直在努力希望 lambdahackers 能给你提供
更高质量的内容和更好的社区，谢谢你对我们的支持!"
   :here-is-what "PRO 用户支持以下特性："
   :no-ads "没有广告。"
   :a-pro-badge "在网站上所有你的头像下面会有一个 PRO 徽章。"
   :more-to-come "PRO 用户将来会拥有更多功能。"
   :pro-costs "PRO 需要 "
   :nine-nine-per-month  "$0.99/每月"
   :you-can-cancel "， 你可以随时取消。"
   :upgrade-to-pro "升级 PRO"
   :login-to-upgrade-to-pro "登录升级 PRO"
   :pricing "价格"
   :thanks-for-your-support "谢谢你的支持!"
   :links "链接"
   :poll "投票"
   :choice "选项"
   :add-a-choice "添加其他选项"
   :choice-votes "投票"
   :choice-saved "谢谢你的投票!"
   :lock-this-poll "锁定投票"
   :delete-this-poll "删除投票"
   :locked "已锁定"
   :set-as-cover "设为封面"
   :save "保存"
   :cover-title "标题"
   :cover-subtitle "副标题"
   :cover-button-text "按钮文字"
   :edit-cover "编辑"
   :upload "上传"
   :photo-deleted "图片已删除。"
   :delete-photo-confirmation "你确定要删除这张照片吗？"
   :report-delete-confirmation "你确定要删除吗?"
   :group-cover-changed "小组封面已切换！"
   :no-replies-yet "暂时还没有评论。"
   :back-to "返回 "
   :not-found "你来到了未知地带。"
   :draft "草稿"
   :drafts "草稿"
   :select-group "选择小组:"
   :saving "保存中..."
   :sort "排序"
   :latest-reply "最近回复"
   :created-at "创建于"
   :last-reply-at "最近回复"
   :updated-at "上次修改时间"
   :lambdahackers-group "Lambdahackers 小组"
   :already-20-groups "你已经加入了 20 个小组, 请先离开某个小组。"
   :loading "加载中..."
   :contact-us "联系我们"
   :website-name "Lambdahackers"
   :popular "热门话题"
   :new-created "最新"
   :bookmark "收藏"
   :unbookmark "取消收藏"
   :bookmarks "收藏"
   :welcome-to-lambdahackers "欢迎来到 Lambdahackers!"
   :activate-your-account "登录"
   :last-reply-by "最近回复: "
   :posted-by "提交: "
   :add-to-wiki "添加到 Wiki"
   :email-login-placeholder "你的邮箱地址"
   :github-connect-text "[NOTE]
====
你可以 git 提交一篇文章到指定的仓库, 这篇文章将会自动发布到 Lambdahackers。
同样你也可以在网站上创建或者编辑某篇文章, 所有修改将会自动提交到你的仓库里。
====

.步骤
****
. 你赋予我们 `public_repo` 权限。

. 我们会创建一个默认仓库 *lambdahackers-blog*, 你可以后续修改名字。

. 我们会在该仓库上添加一个 push hook, 用来监听该仓库所有的提交。
****"
   :report-this-post "举报"
   :delete-this-post "删除"
   :report-this-comment "举报"
   :delete-this-comment "删除"

   ;; post tags
   :add-tags "添加标签 (最多 5 个 )..."
   :email-notification-settings "邮件通知"
   :email-notification-settings-text "当别人回复我或者提及我的用户名邮件通知我"
   :my-data "我的数据"
   :watch "跟踪"
   :watch-text "所有新评论都会收到邮件通知"
   :default "默认"
   :default-text "当有人回复或者提及你时会收到邮件通知"
   :mute "勿扰"
   :mute-text "你不会再收到任何跟这个帖子有关的邮件通知"
   :about-description "Lambdahackers 是一个开源的码农社区。大家可以在这里讨论，提问以及分享自己的文章或作品。"
   :about-text "
=== 功能

* 所有人都可以 *创建任何跟码农有关的小组*。
  小组支持分类。

* 用 *Git* 来发布文章。:tada:
  你可以提交文章到 Github 上，支持 Markdown 和 Asciidoctor 格式，这篇文章将会自动发布到 Lambdahackers， 同样你也可以在网站上创建或者编辑某篇文章, 所有修改将会自动提交到你的仓库里。

* 一个简单的博客。
  支持标签。
  后续会支持其他功能，比如专栏，自定义域名等。

=== FAQ

* Lambdahackers 团队有哪些人？
  目前只有我一人，@tiensonqin。

* 网站免费的话，你怎么赚钱呢？
  1. 我不会出售你的任何个人信息。
  2. 网站只会有很少的广告，比如社区赞助。

* Lambdahackers 用了什么技术？
  前端: https://clojurescript.org/[Clojurescript], https://reactjs.org/[React].
  后端: https://clojure.org/[Clojure], https://www.postgresql.org/[Postgres], https://redis.io/[Redis].

* 我想成为某个小组的管理员，该怎么做？
  你可以联系该组管理员，或者发邮件到: tiensonqin@gmail.com。
"
   })
